[package]
name = "tracy_rust_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracy-client = { version = "0.12.6", default-features = false, features = ["enable"] }
